import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { objectiveKindSchema } from '../packages/shared/src/objective.js';

/**
 * Generates `docs/COVERAGE.md` — what the agent can actually do.
 *
 * Feature completeness is the kind of claim that rots quietly: a capability is
 * added, a doc is not, and six weeks later nobody knows whether the gap in the
 * list is real. So the list of capabilities is derived from the contract that
 * defines them, and CI fails when the committed file disagrees.
 *
 * What is *not* covered still has to be written by hand — absence cannot be
 * derived — but each entry states why, so "missing" and "deliberately out of
 * scope" stay distinguishable.
 *
 * Run: `pnpm docs:coverage` (write) or `pnpm docs:coverage:check` (verify).
 */

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const output = join(repoRoot, 'docs/COVERAGE.md');
const checkOnly = process.argv.includes('--check');

/** Human descriptions, keyed by kind. A kind with none is a hole in the docs. */
const DESCRIPTIONS: Record<string, string> = {
  gather_resource: 'Train any gathering or artisan skill on a chosen recipe',
  sell_items: 'Sell one item stack, keeping a stated quantity',
  buy_shop_upgrade: 'Buy from the shop above a GP floor',
  fight_monster: 'Fight a monster, behind the survivability gate',
  run_dungeon: 'Run a dungeon, gated on its hardest monster',
  tend_farm: 'Plant and harvest farm plots',
  compost_plot: 'Compost a growing plot so the crop cannot die',
  equip_item: 'Equip gear, including mid-fight',
  equip_food: 'Equip food from the bank',
  change_equipment_set: 'Switch between saved loadouts',
  spend_mastery: "Convert a skill's mastery pool into mastery levels",
  set_attack_style: 'Choose which combat skill receives XP',
  toggle_prayer: 'Turn a prayer on or off',
  toggle_curse: 'Turn a curse on or off',
  toggle_aurora: 'Turn an aurora on or off',
  select_spell: 'Choose the attack spell for Magic combat',
  use_potion: 'Drink a potion for the current activity',
  new_slayer_task: 'Take a Slayer task',
  toggle_bank_lock: 'Lock a bank item so selling cannot destroy it',
  upgrade_item: 'Combine bank materials into a better item',
  build_township: 'Build a Township building in a biome',
  repair_township: 'Repair a degraded Township building',
  restore_town_health: 'Spend town resources to restore town health',
  survey_hex: 'Survey the best available Cartography hex',
  excavate_dig_site: 'Excavate an Archaeology dig site',
  select_dig_map: 'Select the map a dig site digs with',
  select_dig_tool: 'Select which tools a dig site uses',
  build_obstacle: 'Build an Agility course obstacle',
  upgrade_constellation: 'Spend stardust on a constellation modifier',
  unlock_skill_node: 'Spend skill points on a skill tree node',
  select_level_cap: 'Choose which skill a level cap increase raises',
  passive_cook: 'Start passive cooking, which runs behind everything else',
  run_golbin_raid: 'Play a Golbin Raid, answering each choice it stops on',
  select_worship: "Choose the town's worship while it is still free",
};

/** Systems with no capability, and why that is the right call. */
const NOT_COVERED: [string, string][] = [
  ['Ancient Relics', 'granted automatically by playing; there is nothing to decide'],
  ['Pets', 'rolled automatically from actions the agent already performs'],
  ['Mastery checkpoints', 'applied by the game the moment the threshold is crossed'],
  ['Bank tabs and sorting', 'cosmetic; no effect on what the character can do'],
  [
    'Switching an existing Township worship',
    'the first choice is a capability; switching later costs 50,000,000 GP and destroys every worship building, so it is not offered beside "build a hut" where a planner skimming labels could pick it',
  ],
  [
    'Item downgrades',
    'destroys the better item for a refund; a real feature, never the right unattended move',
  ],
  ['Abyssal realm content', 'refused by the realm guard, per the original brief'],
];

const kinds = objectiveKindSchema.options;
const missing = kinds.filter((kind) => DESCRIPTIONS[kind] === undefined);
if (missing.length > 0) {
  throw new Error(
    `no description for capability kind(s): ${missing.join(', ')}. Add them to scripts/gen-coverage.ts.`,
  );
}

const lines = [
  '# Coverage',
  '',
  '<!-- Generated by scripts/gen-coverage.ts. Do not edit by hand. -->',
  '',
  `The agent has **${kinds.length} capabilities**. Each is a decision the planner can`,
  'choose and the mod can verify — every one returns before/after evidence rather',
  'than a return value it was told to trust.',
  '',
  '## What the agent can do',
  '',
  '| Capability | What it does |',
  '| --- | --- |',
  ...[...kinds].sort().map((kind) => `| \`${kind}\` | ${DESCRIPTIONS[kind]} |`),
  '',
  '## What it deliberately does not do',
  '',
  '| System | Why not |',
  '| --- | --- |',
  ...NOT_COVERED.map(([system, why]) => `| ${system} | ${why} |`),
  '',
];

const contents = `${lines.join('\n')}`;

if (checkOnly) {
  let committed = '';
  try {
    committed = readFileSync(output, 'utf8');
  } catch {
    console.error('docs/COVERAGE.md is missing. Run: pnpm docs:coverage');
    process.exit(1);
  }

  if (committed !== contents) {
    console.error('docs/COVERAGE.md is out of date. Run: pnpm docs:coverage');
    process.exit(1);
  }

  console.log(`docs/COVERAGE.md is current (${kinds.length} capabilities).`);
} else {
  writeFileSync(output, contents, 'utf8');
  console.log(`Wrote docs/COVERAGE.md (${kinds.length} capabilities).`);
}
